### PR TITLE
Added a feature which will allow us to send response by return a valu…

### PR DESCRIPTION
**Pull request by vikaskandari**
I have added  a feature keeping in mind it will not break older versions.

Feature will allow us to send response simply by returning a value  or promise from controller method.

To make sure this feature will not impact older versions i have added a configuration option which we can use to enable this feature , by default this feature will be turned off. 

to enable this feature we simply have to call following function  before ```attachControllers```

```typescript
setConfiguration({
  return_response: true
});

attachControllers(app, [TestController]);

```

i am adding a simple example or how it will work

```typescript
import express from 'express';
import {Controller,Response,Get,attachControllers,setConfiguration} from '@decorators/express';



function delay(m: number, d: any = {}) {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(d);
    }, m);
  })
}


@Controller('/')
class TestController {

  // Without waiting for promise
  @Get('/without-promise')
   getWithoutPromise(@Response() res) {
    return "This will be sent without delay";
  }

  // Waiting for promise
  @Get('/with-promise')
  async getWithPromise(@Response() res) {
    await delay(5000);
    return "This will be sent after 5 seconds";
  }


  // Returning a  promise
  @Get('/from-promise')
   getFromPromise(@Response() res) {
    return new Promise((resolve)=>{
      resolve("This response will be sent from promise resolve");
    });
  }


  // If we send the response and also returna value then the returned value will not be sent 
  // to prevent form headers already sent error
  @Get('/headers-already-sent-validation')
   getTest(@Response() res) {
    res.send("This will be sent")
    return "But this will not";
  }


}


const app = express();

setConfiguration({
  return_response: true
});

attachControllers(app, [TestController]);

app.listen(3000);

console.log('Server is running on http://localhost:3000');

```

### CODE REVIEW

**Comment by vikaskandari** [comment]
@serhiisol  is this update deployable ? I did test it with playground its working as expected i hope its working fine for you as well , i would love to receive a npm package update as soon as possible because i have started so many projects with node decorators and i really like to contribute more in this plugin to make it more effective and time saving in development .

**Comment by serhiisol** [comment]
Hi @vikaskandari I have few comments to fix and we'll merge it.

**Comment by serhiisol** [comment]
For example, in some cases you would probably need either of the options:
```ts
@Controller('/')
@Injectable()
export class ExpressController {
  @Get('/one')
  one(@Res() res: Response) {
    res.send('Hello res.send world!');
  }

  @Get('/two')
  two() {
	return 'Hello Simple world!';
  }

  @Get('/three')
  async three(@Res() res: Response) {
    await asyncStuff();
	
	return 'Hello Async World!';
  }
}

```

**Comment by Kaizodo** [comment]
Yes i added the configuration to enable disable this feature so if for anyone this feature causes trouble like in older version case they can simply turn off or on, but i also think configuration is not required as we haven't done any breaking change.

**Comment by vikaskandari** [comment]
@serhiisol  when this update is going to be public ? are you adding more features!!!

**Comment by serhiisol** [comment]
PR is almost ready. Did a little bit of overhaul and updated versions of express.

**Comment by serhiisol** [comment]
See #123

**Comment by serhiisol** [comment]
See #123

**Pull request closed without merging**
