### PR TITLE
feat(di): update reflect-metadata to 0.1.13

### PR DESCRIPTION
**Pull request by freemanlam**
I'm trying to make a update of reflect-metadata due to https://github.com/serhiisol/node-decorators/issues/108, but not sure how to manage the updated "@decorators/di" for express and socket packages, hope can this help :)

### CODE REVIEW

**Comment by serhiisol** [comment]
Hi @freemanlam, could you bump the package version ?

**Comment by freemanlam** [comment]
> Hi @freemanlam, could you bump the package version ?

Sure, should I also change the di version in express and socket? Just not sure because the newer version of di is not on npm yet.

**Comment by serhiisol** [comment]
I might be useful, but I believe through the new PR

**Comment by freemanlam** [comment]
Bumped di to 1.0.3 :D

**Review by serhiisol — APPROVED** [review]

**Comment by serhiisol** [comment]
I'll release it tonight

**Comment by freemanlam** [comment]
Cheers!

**Pull request merged**
