### PR TITLE
fix(express-openapi): upgrade `@decorators/di` and use async methods

### PR DESCRIPTION
**Pull request by nassero**

### CODE REVIEW

**Comment by serhiisol** [comment]
Hi @nassero. Could you bump the version and I'll merge it?

**Comment by nassero** [comment]
@serhiisol done and done! Minor seemed to me to be the most appropriate, but if you'd rather it be major/patch, feel free to let me know!

**Comment by serhiisol** [comment]
Could you update package.lock as well? cause it seems to be outdated? :)

**Comment by nassero** [comment]
good catch, sorry I missed it. it's updated.

**Pull request merged**
