### PR TITLE
fix(express-openapi): param schema

### PR DESCRIPTION
**Pull request by nassero**
* add `schema` to `Param()`
* add `options.contentMediaType` to `Param()`

### CODE REVIEW

**Comment by nassero** [comment]
@serhiisol any chance you could give this a review? would love to have this merged for a few of my projects

**Comment by nassero** [comment]
@serhiisol thanks for merging it. I don't see it published just yet, could you please do that when you get a chance? Thanks!

**Comment by serhiisol** [comment]
@nassero I'll release it tonight.

**Comment by serhiisol** [comment]
@nassero It's released. Have fun :)

**Pull request merged**
