### PR TITLE
OpenApi decorators implementation + swagger ui

### PR DESCRIPTION
**Pull request by MarceloAplanalp**
As suggested on #81

### CODE REVIEW

**Comment by serhiisol** [comment]
Super awesome 👍 I'll review the PRs asap

**Comment by serhiisol** [comment]
Could you remove example folder and create another PR into https://github.com/serhiisol/node-decorators-playground ? I'll merge and release this :)

**Comment by potitoaghilar** [comment]
Is there any update on this PR @serhiisol?

**Comment by wazzu3000** [comment]
Do you have any news about this PR @serhiisol ?

**Comment by serhiisol** [comment]
Wow, that was hell of a ride last year. I'm going to review it right now :)

**Comment by serhiisol** [comment]
@MarceloAplanalp what do you think if me combine express and openapi into one package?

**Comment by serhiisol** [comment]
I'll merge this PR and do some adjustments before release :)

**Comment by darek-phorest** [comment]
hi @serhiisol 👋 , do you have any date for the release of those decorators ?

**Comment by gurkansahinn** [comment]
:bump:

**Pull request merged**
